version: "3.7"

services:
  frontend:
    depends_on:
      - backend
    build: ./frontend # link to subfolder of mono-repo
    command: ts-node node_modules/.bin/gatsby develop -H 0.0.0.0 -p 3000
    volumes:
      - ./frontend:/app
    restart: "no"
    # allows the frontend to access the backend at localhost, which allows Gatsby to access the api
    # and the Api to include localhost:8000 (and not backend:8000) in the image paths.
    network_mode: "service:backend"
  backend:
    # You could define your backend service here.